// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://locqpeakoqrliwitbgbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY3FwZWFrb3FybGl3aXRiZ2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTg2OTMsImV4cCI6MjA1MDE5NDY5M30.PfQm833tbrycLKCNQGtg9f-iU0gIGJe4prMAVwNKv20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);